name: lifevora_app
description: Lifevora - Fitness & Well-Being Tracker
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  fl_chart: ^0.68.0
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  hugeicons: ^0.0.7
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/ar_avatar/